export const $ = (s) => document.querySelector(s);
export const els = {
  answers: $('#answers'),
  question: $('#question'),
  roundLabel: $('#roundLabel'),
  multLabel: $('#multLabel'),
  multPill:  $('#multPill'),
  phaseLabel: $('#phaseLabel'),
  poolTop:   $('#poolTop'),
  pool:      $('#pool'),
  scoreA:    $('#scoreA'),
  scoreB:    $('#scoreB'),
  labelA:    $('#labelA'),
  labelB:    $('#labelB'),
  teamA:     $('#teamA'),
  teamB:     $('#teamB'),
  nameA:     $('#nameA'),
  nameB:     $('#nameB'),
  startTeam: $('#startTeam'),
  toast:     $('#toast'),
  overlayX:  $('#overlayX'),
  overlayXText: $('#overlayXText'),
  chkRandom: $('#chkRandom'),
  inpThreshold: $('#inpThreshold'),
  errorBox:  $('#errorBox'),
  btnReset:  $('#btnReset'),
  welcome:  $('#welcome'),
  wNameA:   $('#wNameA'),
  wNameB:   $('#wNameB'),
  wStart:   $('#wStartTeam'),
  wStartBtn:$('#wStartBtn'),

};
